### ISSUE TITLE
typo in deeplearning2020/tests/test_deeplearning2020.py

### ISSUE THREAD

**Issue by Brotherlui** [into-ai/deeplearning2020#1]
Hallöchen, so beim drüber schauen ist mir vermutlich ein Typo aufgefallen:

test_deeplearning2020.py, Zeile 36  

`def test_ingores_exceptions() -> None:`

soll vermutlich

`def test_ignores_exceptions() -> None:`

lauten. (2+3 Buchstabe vertauscht)

Viele Grüße
Thomas

**Comment by romnnn** [comment]
Vielen Dank!
