### ISSUE TITLE
helpers.py zerschossen

### ISSUE THREAD

**Issue by Brotherlui** [into-ai/deeplearning2020#8]
die helpers.py wurde zerschossen!
Warum ändert @hndrkp
import matplotlib.pyplot as plt in import matplogitlib.pyplot as plt

**Comment by romnnn** [comment]
Vielen Dank für den Hinweis!

@hndrkp ist auch nur ein Mensch und Fehler passieren nun mal. Ein möglicher Tat-Hergang könnte gewesen sein, dass im Terminal `git` benutzt wurde, aber der Fokus der Eingabe noch in der IDE war.

Beste Grüße, Roman
